ACR_NAME: "{{ lookup('env', 'ACR_USERNAME') }}"
ACR_USERNAME: "{{ lookup('env', 'ACR_USERNAME') }}"
ACR_PASSWORD: "{{ lookup('env', 'ACR_PASSWORD') }}"
ACR_LOGIN_SERVER: "acrdevcp2.azurecr.io"
IMAGE1_NAME: "nginx"
IMAGE2_NAME: "jenkins"
IMAGE_TAG: "casopractico2"
RESOURCE_GROUP_NAME: "rg-azure-infra-deploy" 
ansible_user_id: "keji"
storage_class_name: "default"  
